const dummyProducts = [
  // Arche
  {
    name: "AR 31",
    productName: "Arche",
    des: [
      "Introducing the AR 31 Wireless Microphone System with Advanced Features:",
      "- Automatic Frequency Selection (AFS): Press the “/” button for 3 seconds, and the receiver will perform an automatic scan, locking onto an open, interference-free frequency for optimal performance.",
      "- Compatible Systems: With the capability to use multiple frequency bands in one venue, the AR 31 supports up to 24 sets simultaneously, ensuring a seamless and interference-free audio experience.",
      "- IR Infrared Sync: Easily pair the receiver frequency with the transmitter by pressing the [IR] button, simplifying setup and synchronization for hassle-free operation.",
      "- Full Band Transmitter: Equipped with a 134MHz full band transmitter, the AR 31 allows pairing with the receiver irrespective of the frequency band, providing versatility and flexibility.",
      '- Anti-Interference: Featuring a PLL (Phase Lock Loop) frequency control design, the AR 31 ensures transmission reliability. The "NoiseLock" squelch effectively blocks stray RF, maintaining clear and crisp audio.',
      "- Energy Conservation: Switch to the Low RF power mode to double the battery life, offering up to 14 hours* on AA Alkaline Batteries. This energy-efficient design ensures prolonged use without compromising performance.",
    ],
    category: "Wireless Microphone Systems",
    description:
      "AR3 is a 1/2 EIA standard Rack Unit metal chassis single-channel wireless receiver for AR1 & AR2 transmitters. Bright & intuitive LCD front panel display gives necessary information like RF level, Audio levels, working channel & transmitter battery status, etc. With 32MHz operating bandwidth, each receiver band allows up to 10 compatible systems which are interference-free. With multiple bands, it can reach up to 24 compatible systems*. The PLL synthesized circuitry ensures RF transmission reliability with separation from GSM & other EMI interference. AFS (Auto Frequency Selection) functions scan the environment and lock itself in an open interference-free frequency channel. The diversity antenna circuit chooses the better one receiving out of its 1/2 Wave Antennae to give optimum RF stability every time.",
    technicalSpecification: {
      "Carrier Frequency Range": "522MHz~936MHz",
      "Modulation Mode": "FM stere modulation",
      Oscillation: "PLL synthesized",
      Sensitivity: "5dBμV, S/N>60dB at 25 deviation",
      "Operating Bandwidth": "32MHz (E, I, J, K)",
      "Max. Deviation Range": "±45KHz",
      "S/N Ratio": ">105dB",
      "T. H. D": "<0.7%@1KHz",
      "Frequency Response (audio)": "45Hz-18KHz ±3dB",
      "Operating Range": "100M typical*",
      "Power Supply": "DC 12V/12W adapter",
      "Dimension (mm)": "20 (W)x206(D)x43(H)",
      Weight: "Approximately 1.0kg",
      "Output Connector": "XLR balanced & 6.3φ phone jack unbalanced",
      Housing: "Pressed steel powder coated enclosure",
    },
    keyFeatures: [
      "Key Features",
      "AFS (Automatic Frequency Selection)",
      "Press the “AFS” (Auto Frequency Selection) button 3 sec and the receiver will auto-scan and lock on to an open, interference-free frequency.",
      "Compatible systems",
      "Maximum 24 sets can be used simultaneously by using multiple frequency bands in one venue.",
      "IR Infrared Sync",
      "Press [IR] button to automatically pair the receiver frequency with the transmitter.",
      "Full Band Transmitter",
      "134MHz full band transmitter allows pairing with the receiver irrespective of frequency band.",
      "Anti-Interference",
      "PLL (Phase Lock Loop frequency control) design ensures transmission reliability, “NoiseLock”squelch effectively blocks stray RF.",
      "Energy Conservation",
      "Low RF power mode gives twice the battery life of up to 14 hours*. (On AA Alkaline Batteries)",
    ],
    image: require("../../assets/Arche/Arche-31/Ar31.png"),
    download:
      "https://drive.google.com/file/d/1UNgmmpi69DCYuxc9GulFa8Ogw4fi6kBN/view?usp=drive_link",
  },
  {
    name: "AR 32",
    productName: "Arche",
    des: [
      "Introducing the AR 31 Wireless Microphone System with Advanced Features:",
      "- AFS (Automatic Frequency Selection) : Press the “/“ button for 3 sec and the receiver will auto-scan and lock on to an open, interference-free frequency.",
      "- Compatible systems : Maximum 24 sets can be used simultaneously by using multiple frequency bands in one venue.",
      "- IR Infrared Sync : Press [IR] button to automatically pair the receiver frequency with the transmitter.",
      "- Full Band Transmitter : 134MHz full band transmitter allows pairing with the receiver irrespective of frequency band.",
      "- Anti-Interference : PLL (Phase Lock Loop frequency control) design ensures transmission reliability, “NoiseLock”squelch effectively blocks stray RF.",
      "- Energy Conservation : Low RF power mode gives twice the battery life of up to 14 hours*. (On AA Alkaline Batteries)",
    ],
    category: "Wireless Microphone Systems",
    description:
      "AR3 is a 1/2 EIA standard Rack Unit metal chassis single-channel wireless receiver for AR1 & AR2 transmitters. Bright & intuitive LCD front panel display gives necessary information like RF level, Audio levels, working channel & transmitter battery status, etc. With 32MHz operating bandwidth, each receiver band allows up to 10 compatible systems which are interference-free. With multiple bands, it can reach up to 24 compatible systems*. The PLL synthesized circuitry ensures RF transmission reliability with separation from GSM & other EMI interference. AFS (Auto Frequency Selection) functions scan the environment and lock itself in an open interference-free frequency channel. The diversity antenna circuit chooses the better one receiving out of its 1/2 Wave Antennae to give optimum RF stability every time.",
    technicalSpecification: {
      "Carrier Frequency Range": "522MHz~936MHz",
      "Modulation Mode": "FM stere modulation",
      Oscillation: "PLL synthesized",
      Sensitivity: "5dBμV, S/N>60dB at 25 deviation",
      "Operating Bandwidth": "32MHz (E, I, J, K)",
      "Max. Deviation Range": "±45KHz",
      "S/N Ratio": ">105dB",
      "T. H. D": "<0.7%@1KHz",
      "Frequency Response (audio)": "45Hz-18KHz ±3dB",
      "Operating Range": "100M typical*",
      "Power Supply": "DC 12V/12W adapter",
      "Dimension (mm)": "20 (W)x206(D)x43(H)",
      Weight: "Approximately 1.0kg",
      "Output Connector": "XLR balanced & 6.3φ phone jack unbalanced",
      Housing: "Pressed steel powder coated enclosure",
    },
    keyFeatures: [
      "Key Features",
      "AFS (Automatic Frequency Selection)",
      "Press the “AFS” (Auto Frequency Selection) button 3 sec and the receiver will auto-scan and lock on to an open, interference-free frequency.",
      "Compatible systems",
      "Maximum 24 sets can be used simultaneously by using multiple frequency bands in one venue.",
      "IR Infrared Sync",
      "Press [IR] button to automatically pair the receiver frequency with the transmitter.",
      "Full Band Transmitter",
      "134MHz full band transmitter allows pairing with the receiver irrespective of frequency band.",
      "Anti-Interference",
      "PLL (Phase Lock Loop frequency control) design ensures transmission reliability, “NoiseLock”squelch effectively blocks stray RF.",
      "Energy Conservation",
      "Low RF power mode gives twice the battery life of up to 14 hours*. (On AA Alkaline Batteries)",
    ],
    image: require("../../assets/Arche/Arche-32/AR32.png"),
    download:
      "https://drive.google.com/file/d/1aOBFmLVdC00hl3wRUOjH-iQrUJ_7x0Nl/view?usp=drive_link",
  },
  {
    name: "AR 331",
    productName: "Arche",

    des: [
      "Introducing the AR 31 Wireless Microphone System with Advanced Features:",
      "-AFS (Automatic Frequency Selection) : Press the “/“ button for 3 sec and the receiver will auto-scan and lock on to an open, interference-free frequency.",
      "- Compatible systems : Maximum 24 sets can be used simultaneously by using multiple frequency bands in one venue.",
      "- IR Infrared Sync : Press [IR] button to automatically pair the receiver frequency with the transmitter.",
      "- Full Band Transmitter : 134MHz full band transmitter allows pairing with the receiver irrespective of frequency band.",
      "- Anti-Interference : PLL (Phase Lock Loop frequency control) design ensures transmission reliability, “NoiseLock”squelch effectively blocks stray RF.",
      "- Energy Conservation : Low RF power mode gives twice the battery life of up to 14 hours*. (On AA Alkaline Batteries)",
    ],
    category: "Wireless Microphone Systems",
    description:
      "AR33 is a dual channel wireless receiver for AR1 & AR2 transmitters housed in 1 EIA standard Rack Unit metal chassis. Bright & intuitive LCD front panel display gives the necessary information for both the transmitters like RF level, Audio levels, working channel & transmitter battery status, etc. With 32MHz operating bandwidth for each receiver, the band allows up to 10 compatible systems which are interference-free. With multiple bands, it can reach up to 24 compatible systems*. The PLL synthesized circuitry ensures RF transmission reliability with separation from GSM & other EMI interference. AFS (Auto Frequency Selection) functions scan the environment and lock itself in an open interference-free frequency channel. The diversity antenna circuit chooses the better one receiving out of its 1/2 Wave Antennae to give optimum RF stability every time.",
    technicalSpecification: {
      "Mainframe Size": "EIA Standard 1U",
      Channels: "Dual Channel",
      "Frequency Stability": "±0.0005% (0~50 °C)",
      "Carrier Frequency Range": "522MHz~936MHz",
      "Modulation Mode": "FM stereo modulation",
      Oscillation: "PLL synthesized",
      "Receiving Sensitivity": "5dBuv, S/N>60dB",
      Bandwidth: "at 25 deviation 32MHz",
      "Max. Deviation Range": "±45KHz",
      "S/N Ratio": ">105dB",
      "Total Harmonic Distortion (T.H.D)": "<0.7%@1KHz",
      "Frequency Response": "80Hz-18KHz ±3dB",
      "Operating Range": "80~100M typical (in open space)",
      "Power Supply": "DC 12V/12W",
      Weight: "1.9kg",
      "Dimension (mm)": "410(W) x 206 (D) x 43 (H)",
      "Output Connector": "XLR balanced & 6.3 φ phone jack unbalanced",
    },
    keyFeatures: [
      "AFS (Automatic Frequency Selection)",
      "Press the “AFS” (Auto Frequency Selection) button 3 sec and the receiver will auto-scan and lock on to an open, interference-free frequency.",
      "Compatible Systems",
      "Maximum 24 sets can be used simultaneously by using multiple frequency bands in one venue.",
      "IR Infrared Sync",
      "Press [IR] button to automatically pair the receiver frequency with the transmitter.",
      "Full Band Transmitter",
      "134MHz full band transmitter allows pairing with the receiver irrespective of frequency band.",
      "Anti-Interference",
      "PLL (Phase Lock Loop frequency control) design ensures transmission reliability, “NoiseLock” squelch effectively blocks stray RF.",
      "Energy Conservation",
      "Low RF power mode gives twice the battery life of up to 14 hours*. (On AA Alkaline Batteries)",
    ],
    image: require("../../assets/Arche/Arche-331/AR331.png"),
    download:
      "https://drive.google.com/file/d/1KaAtpZaUaNC_3BJBwJCzZ94RHpYPcOAq/view?usp=drive_link",
  },
  {
    name: "AR 332",
    productName: "Arche",

    des: [
      "Introducing the AR 31 Wireless Microphone System with Advanced Features:",
      "-AFS (Automatic Frequency Selection) : Press the “/“ button for 3 sec and the receiver will auto-scan and lock on to an open, interference-free frequency.",
      "- Compatible systems : Maximum 24 sets can be used simultaneously by using multiple frequency bands in one venue.",
      "- IR Infrared Sync : Press [IR] button to automatically pair the receiver frequency with the transmitter.",
      "- Full Band Transmitter : 134MHz full band transmitter allows pairing with the receiver irrespective of frequency band.",
      "- Anti-Interference : PLL (Phase Lock Loop frequency control) design ensures transmission reliability, “NoiseLock”squelch effectively blocks stray RF.",
      "- Energy Conservation : Low RF power mode gives twice the battery life of up to 14 hours*. (On AA Alkaline Batteries)",
    ],
    category: "Wireless Microphone Systems",
    description:
      "AR33 is a dual channel wireless receiver for AR1 & AR2 transmitters housed in 1 EIA standard Rack Unit metal chassis. Bright & intuitive LCD front panel display gives the necessary information for both the transmitters like RF level, Audio levels, working channel & transmitter battery status, etc. With 32MHz operating bandwidth for each receiver, the band allows up to 10 compatible systems which are interference-free. With multiple bands, it can reach up to 24 compatible systems*. The PLL synthesized circuitry ensures RF transmission reliability with separation from GSM & other EMI interference. AFS (Auto Frequency Selection) functions scan the environment and lock itself in an open interference-free frequency channel. The diversity antenna circuit chooses the better one receiving out of its 1/2 Wave Antennae to give optimum RF stability every time.",
    technicalSpecification: {
      "Mainframe Size": "EIA Standard 1U",
      Channels: "Dual Channel",
      "Frequency Stability": "±0.0005% (0~50 °C)",
      "Carrier Frequency Range": "522MHz~936MHz",
      "Modulation Mode": "FM stereo modulation",
      Oscillation: "PLL synthesized",
      "Receiving Sensitivity": "5dBuv, S/N>60dB",
      Bandwidth: "at 25 deviation 32MHz",
      "Max. Deviation Range": "±45KHz",
      "S/N Ratio": ">105dB",
      "Total Harmonic Distortion (T.H.D)": "<0.7%@1KHz",
      "Frequency Response": "80Hz-18KHz ±3dB",
      "Operating Range": "80~100M typical (in open space)",
      "Power Supply": "DC 12V/12W",
      Weight: "1.9kg",
      "Dimension (mm)": "410(W) x 206 (D) x 43 (H)",
      "Output Connector": "XLR balanced & 6.3 φ phone jack unbalanced",
    },
    keyFeatures: [
      "AFS (Automatic Frequency Selection)",
      "Press the “AFS” (Auto Frequency Selection) button 3 sec and the receiver will auto-scan and lock on to an open, interference-free frequency.",
      "Compatible Systems",
      "Maximum 24 sets can be used simultaneously by using multiple frequency bands in one venue.",
      "IR Infrared Sync",
      "Press [IR] button to automatically pair the receiver frequency with the transmitter.",
      "Full Band Transmitter",
      "134MHz full band transmitter allows pairing with the receiver irrespective of frequency band.",
      "Anti-Interference",
      "PLL (Phase Lock Loop frequency control) design ensures transmission reliability, “NoiseLock” squelch effectively blocks stray RF.",
      "Energy Conservation",
      "Low RF power mode gives twice the battery life of up to 14 hours*. (On AA Alkaline Batteries)",
    ],
    image: require("../../assets/Arche/Arche-332/AR332.png"),
    download:
      "https://drive.google.com/file/d/1Fw_fNaB_vcr0V4LJYmb18LAZKJx_nKx4/view?usp=drive_link",
  },
  {
    name: "AR1 HANDHELD TRANSMITTER",
    productName: "Arche",
    des: [
      "Dynamic Unidirectional microphone for music & speech.",
      "Wide Operating Bandwidth of 134 MHz.",
      "Operating distance of up to 100 meters.",
      "RF Boost & Battery saver mode switchable (10/40mW).",
      "OLED display provides frequency, channel & battery status.",
      "Operating time of up to 14 hours on AA Alkaline batteries (battery saver mode).",
      "Durable metal die-cast body.",
    ],
    category: "Wireless Microphone Systems",
    image: require("../../assets/Arche/Arche-31/AR3.png"),
  },
  {
    name: "AR2 BODYPACK TRANSMITTER",
    productName: "Arche",
    des: [
      "Dynamic Unidirectional microphone for music & speech.",
      "Wide Operating Bandwidth of 134 MHz.",
      "Operating distance of up to 100 meters.",
      "RF Boost & Battery saver mode switchable (10/40mW).",
      "OLED display provides frequency, channel & battery status.",
      "Operating time of up to 14 hours on AA Alkaline batteries (battery saver mode).",
      "Durable metal die-cast body.",
    ],
    category: "Wireless Microphone Systems",
    image: require("../../assets/Arche/Arche-31/AR3.png"),
  },
  {
    name: "AR3 SINGLE CHANNEL DIVERSITY RECEIVER",
    productName: "Arche",
    des: [
      "UHF Band Single Channel diversity receiver.",
      "PLL Synthesised circuitry with RF separation from GSM networks.",
      "Auto Frequency Scan & Noise Squelch adjustment.",
      "32MHz operating bandwidth to allow 10 compatible systems working seamlessly.",
      "Up to 24 compatible systems on multiple frequency bands.",
      "Bright & Intuitive LCD display for RF level, Audio levels, working channel & transmitter battery status.",
      "Rugged 1/2 EIA standard rack unit enclosure made with powder coated pressed steel.",
    ],
    category: "Wireless Microphone Systems",
    image: require("../../assets/Arche/Arche-31/AR3.png"),
  },
  {
    name: "AR33 DUAL CHANNEL DIVERSITY RECEIVER",
    productName: "Arche",
    des: [
      "Rugged 1/2 EIA standard rack unit enclosure made with powder coated pressed steel.",
      "UHF Band Dual Channel diversity receiver.",
      "PLL Synthesised circuitry with RF separation from GSM networks.",
      "Auto Frequency Scan & Noise Squelch adjustment.",
      "32MHz operating bandwidth to allow 10 compatible systems working seamlessly.",
      "Up to 24 compatible systems on multiple frequency bands.",
      "Bright & Intuitive LCD display for RF level, Audio levels, working channel & transmitter battery status.",
    ],
    category: "Wireless Microphone Systems",
    image: require("../../assets/Arche/Arche-331/AR331.png"),
  },

  // DSP & Controls
  {
    name: "Keyer 1616",
    productName: "Keyer",
    des: ["16 input 16 output digital signal processor with AEC"],
    category: "DSP & Controls",
    description:
      "The KEYER 1616 is an audio processing and control system that uses an advanced TI456MHz Dual-Core Chip for DSP giving you an unprecedented opportunity to solve the most complex problems of signal routing & processing. Keyer 1616 makes mixing, signal routing, vocal processing, and room optimisation, all these tasks, are very simple and quite straightforward. The Keyer Series DSP helps you to get the most optimised audio performance for presentation and conferencing applications in wherever place you want whether it be in boardrooms, courtrooms, or a restro-bar.",
    technicalSpecification: {
      "Sampling Rate": "48KHz",
      "Phantom Power": "48V",
      "Frequency Response": "20 – 20KHz，±0.2dB",
      "Maximum Input/Output Level": "18dBu",
      "Output Impedance (Balanced)": "100Ω",
      "Equivalent Input Noise EIN": "≤-125dBU",
      "Channel Isolation @1kHz": "100dB",
      "THD+N": "<0.004% @4dBu",
      "Digital/Analog Dynamic Range": "120dB",
      "Background Noise": "-90dBU",
      "Analog/Digital Dynamic Range": "114dB",
      "Input Impedance (Balanced)": "20kΩ",
      "Input Gain Amplification Range": "24 to -27dB, (3dB Step, 17 in total)",
      "Operating Power Supply": "AC110/220V,50Hz/60Hz",
      "Enclosure / Chassis Material": "Pressed Steel (powder coated)",
      "Chassis Dimensions (H×W×D)": "45×482×258 mm, Size 19” 1RU",
      "Product Weight": "2.9 kg",
      "Included Accessories": "IEC 1.2 MTR Power Cord",
      "Environmental Conditions": "-10 to +40 °C",
      Compliance: "CE & RoHS",
      "Analog Input Channels": 16,
      "Analog Output Channels": 16,
      "Dante Input Channels": "N/A",
      "Dante Output Channels": "N/A",
      "Ethernet Control Ports": 1,
      "Dante Interface (Primary)": "N/A",
      "Dante Interface (Secondary)": "N/A",
      RS232: 1,
      RS485: 1,
      GPIO: 8,
    },
    keyFeatures: [
      "DSP audio processing",
      "Built-in automatic mixing console",
      "Ducker dodger",
      "Optional feedback elimination",
      "Echo elimination",
      "Noise elimination module",
      "Input Per Channel: Preamplifier, signal generator, expander, compressor, 10-band parametric equalization",
      "Output Per Channel: 31-band graphic equalizer, delay, crossover, limiter",
      "Built-in bi-directional USB Audio Interface for soft codec conferencing solution supports recording & play",
      "Support for scene preset function",
      "Automatic power failure protection memory function",
      "Full-featured matrix mixing function",
      "User definable GUI windows-based control software to manage & configure the DSP unit",
      "Built-in automatic camera tracking function",
    ],
    image: require("../../assets/Keyer/Keyer-88/88 front.png"),
    download:
      "https://drive.google.com/file/d/1RPjiJMP2ahwyhTGpQdeYh5j8BkZE4qpl/view?usp=drive_link",
  },
  {
    name: "Keyer 1616D",
    productName: "Keyer",
    des: ["16 input 16 output digital signal processor with AEC & Dante"],
    category: "DSP & Controls",
    description:
      "The KEYER 1616D is an audio processing and control system that uses an advanced TI456MHz Dual-Core Chip for DSP giving you an unprecedented opportunity to solve the most complex problems of signal routing & processing. The Dante module provides a high bandwidth, low latency, high compatibility, and low-cost solution for network audio transmission. Keyer 1616D makes mixing, signal routing, vocal processing, and room optimisation, all these tasks, are very simple and quite straightforward. The Keyer Series DSP helps you to get the most optimised audio performance for presentation and conferencing applications in wherever place you want whether it be in boardrooms, courtrooms, or a restro-bar.",
    technicalSpecification: {
      "Sampling Rate": "48KHz",
      "Phantom Power": "48V",
      "Frequency Response": "20 – 20KHz，±0.2dB",
      "Maximum Input/Output Level": "18dBu",
      "Output Impedance (Balanced)": "100Ω",
      "Equivalent Input Noise EIN": "≤-125dBU",
      "Channel Isolation @1kHz": "100dB",
      "THD+N": "<0.004% @4dBu",
      "Digital/Analog Dynamic Range": "120dB",
      "Background Noise": "-90dBU",
      "Analog/Digital Dynamic Range": "114dB",
      "Input Impedance (Balanced)": "20kΩ",
      "Input Gain Amplification Range": "24 to -27dB, (3dB Step, 17 in total)",
      "Operating Power Supply": "AC110/220V,50Hz/60Hz",
      "Enclosure / Chassis Material": "Pressed Steel (powder coated)",
      "Chassis Dimensions (H×W×D)": "45×482×258 mm, Size 19” 1RU",
      "Product Weight": "2.9 kg",
      "Included Accessories": "IEC 1.2 MTR Power Cord",
      "Environmental Conditions": "-10 to +40 °C",
      Compliance: "CE & RoHS",
      "Analog Input Channels": 16,
      "Analog Output Channels": 16,
      "Dante Input Channels": 16,
      "Dante Output Channels": 16,
      "Ethernet Control Ports": 1,
      "Dante Interface (Primary)": 1,
      "Dante Interface (Secondary)": 1,
      RS232: 1,
      RS485: 1,
      GPIO: 8,
    },
    keyFeatures: [
      "DSP audio processing",
      "Built-in automatic mixing console",
      "Ducker dodger",
      "Optional feedback elimination",
      "Echo elimination",
      "Noise elimination module",
      "Input Per Channel: Preamplifier, signal generator, expander, compressor, 10-band parametric equalization",
      "Output Per Channel: 31-band graphic equalizer, delay, crossover, limiter",
      "Built-in bi-directional USB Audio Interface for soft codec conferencing solution supports recording & play",
      "Built-in 16×16 Dante audio module",
      "Support for scene preset function",
      "Automatic power failure protection memory function",
      "Full-featured matrix mixing function",
      "User definable GUI windows-based control software to manage & configure the DSP unit",
      "Built-in automatic camera tracking function",
    ],
    image: require("../../assets/Keyer/Keyer-44/44 front.png"),
    download:
      "https://drive.google.com/file/d/1D0HS25JmKmacLVH-g2oduZy-NLHClLM9/view?usp=drive_link",
  },
  {
    name: "Keyer 44",
    productName: "Keyer",
    des: ["4 input 4 out digital signal processor with AEC"],
    category: "DSP & Controls",
    description:
      "The KEYER 44 is an audio processing and control system that uses an advanced TI456MHz Dual-Core Chip for DSP giving you an unprecedented opportunity to solve the most complex problems of signal routing & processing. Keyer44 makes mixing, vocal processing, signal routing & room optimisation all these tasks very simple & straight forward. The Keyer Series DSP helps you to get the most optimised audio performance for presentation and conferencing applications in wherever place you want whether it be in boardrooms, courtrooms, or a resto-bar.",
    technicalSpecification: {
      "Sampling Rate": "48KHz",
      "Phantom Power": "48V",
      "Frequency Response": "20 – 20KHz，±0.2dB",
      "Maximum Input/Output Level": "18dBu",
      "Output Impedance (Balanced)": "100Ω",
      "Equivalent Input Noise EIN": "≤-125dBU",
      "Channel Isolation @1kHz": "100dB",
      "THD+N": "<0.004% @4dBu",
      "Digital/Analog Dynamic Range": "120dB",
      "Background Noise": "-90dBU",
      "Analog/Digital Dynamic Range": "114dB",
      "Input Impedance (Balanced)": "20kΩ",
      "Input Gain Amplification Range": "24 to -27dB, (3dB Step,17 in total)",
      "Operating Power Supply": "AC110/220V,50Hz/60Hz",
      "Enclosure / Chassis Material": "Pressed Steel (powder coated)",
      "Chassis Dimensions (H×W×D)": "45×482×258 mm, Size 19” 1RU",
      "Product Weight": "2.9 kg",
      "Included Accessories": "IEC 1.2 MTR Power Cord",
      "Environmental Conditions": "-10 to +40 °C",
      Compliance: "CE & RoHS",
      "Analog Input Channels": 4,
      "Analog Output Channels": 4,
      "Dante Input Channels": "N/A",
      "Dante Output Channels": "N/A",
      "Ethernet Control Ports": 1,
      "Dante Interface (Primary)": "N/A",
      "Dante Interface (Secondary)": "N/A",
      RS232: 1,
      RS485: 1,
      GPIO: 8,
    },
    keyFeatures: [
      "DSP audio processing",
      "Built-in automatic mixing console",
      "Ducker dodger",
      "Optional feedback elimination",
      "Echo elimination",
      "Noise elimination module",
      "Input Per Channel: Preamplifier, signal generator, expander, compressor, 10-band parametric equalization",
      "Output Per Channel: 31-band graphic equalizer, delay, crossover, limiter",
      "Built-in bi-directional USB Audio Interface for soft codec conferencing solution supports recording & play",
      "Support for scene preset function",
      "Automatic power failure protection memory function",
      "Full-featured matrix mixing function",
      "User definable GUI windows-based control software to manage & configure the DSP unit",
      "Built-in automatic camera tracking function",
    ],
    image: require("../../assets/Keyer/Keyer-44/44 BACK.png"),
    download:
      "https://drive.google.com/file/d/1-iqYA7XdNVx2xIPb1SwCOEmRkMo7tdui/view?usp=drive_link",
  },
  {
    name: "Keyer 88",
    productName: "Keyer",
    des: ["8 input 8 output digital processor with AEC"],
    category: "DSP & Controls",
    description:
      "The KEYER 88 is an audio processing and control system that uses an advanced TI456MHz Dual-Core Chip for DSP giving you an unprecedented opportunity to solve the most complex problems of signal routing & processing. Keyer Series makes mixing, signal routing, vocal processing, and room optimisation, all these tasks very simple and quite straightforward. The Keyer Series DSP helps you to get the most optimised audio performance for presentation and conferencing applications in wherever place you want whether it be in boardrooms, courtrooms, or a resto-bar.",
    technicalSpecification: {
      "Sampling Rate": "48KHz",
      "Phantom Power": "48V",
      "Frequency Response": "20 – 20KHz，±0.2dB",
      "Maximum Input/Output Level": "18dBu",
      "Output Impedance (Balanced)": "100Ω",
      "Equivalent Input Noise EIN": "≤-125dBU",
      "Channel Isolation @1kHz": "100dB",
      "THD+N": "<0.004% @4dBu",
      "Digital/Analog Dynamic Range": "120dB",
      "Background Noise": "-90dBU",
      "Analog/Digital Dynamic Range": "114dB",
      "Input Impedance (Balanced)": "20kΩ",
      "Input Gain Amplification Range": "24 to -27dB, (3dB Step,17 in total)",
      "Operating Power Supply": "AC110/220V,50Hz/60Hz",
      "Enclosure / Chassis Material": "Pressed Steel (powder coated)",
      "Chassis Dimensions (H×W×D)": "45×482×258 mm, Size 19” 1RU",
      "Product Weight": "2.9 kg",
      "Included Accessories": "IEC 1.2 MTR Power Cord",
      "Environmental Conditions": "-10 to +40 °C",
      Compliance: "CE & RoHS",
      "Analog Input Channels": 8,
      "Analog Output Channels": 8,
      "Dante Input Channels": "N/A",
      "Dante Output Channels": "N/A",
      "Ethernet Control Ports": 1,
      "Dante Interface (Primary)": "N/A",
      "Dante Interface (Secondary)": "N/A",
      RS232: 1,
      RS485: 1,
      GPIO: 8,
    },

    keyFeatures: [
      "DSP audio processing",
      "Built-in automatic mixing console",
      "Ducker dodger",
      "Optional feedback elimination",
      "Echo elimination",
      "Noise elimination module",
      "Input Per Channel: Preamplifier, signal generator, expander, compressor, 10-band parametric equalization",
      "Output Per Channel: 31-band graphic equalizer, delay, crossover, limiter",
      "Built-in bi-directional USB Audio Interface for soft codec conferencing solution supports recording & play",
      "Support for scene preset function",
      "Automatic power failure protection memory function",
      "Full-featured matrix mixing function",
      "User definable GUI windows-based control software to manage & configure the DSP unit",
      "Built-in automatic camera tracking function",
    ],
    image: require("../../assets/Keyer/Keyer-1616/1616 BACK.png"),
    download:
      "https://drive.google.com/file/d/1-iqYA7XdNVx2xIPb1SwCOEmRkMo7tdui/view?usp=drive_link",
  },
  {
    name: "Keyer 88D",
    productName: "Keyer",
    des: ["8 input 8 output digital processor with AEC"],
    category: "DSP & Controls",
    description:
      "TThe KEYER 88D is an audio processing and control system that uses an advanced TI456MHz Dual-Core Chip for DSP giving you an unprecedented opportunity to solve the most complex problems of signal routing & processing. The Dante module provides a high bandwidth, low latency, high compatibility, and low-cost solution for network audio transmission. Keyer 88D makes mixing, signal routing, vocal processing, and room optimisation, all these tasks, are very simple and quite straightforward. The Keyer Series DSP helps you to get the most optimised audio performance for presentation and conferencing applications in wherever place you want whether it be in boardrooms, courtrooms, or a resto-bar.",
    technicalSpecification: {
      "Sampling Rate": "48KHz",
      "Phantom Power": "48V",
      "Frequency Response": "20 – 20KHz, ±0.2dB",
      "Maximum Input/Output Level": "18dBu",
      "Output Impedance (Balanced)": "100Ω",
      "Equivalent Input Noise EIN": "≤-125dBU",
      "Channel Isolation @1kHz": "100dB",
      "THD+N": "<0.004% @4dBu",
      "Digital/Analog Dynamic Range": "120dB",
      "Background Noise": "-90dBU",
      "Analog/Digital Dynamic Range": "114dB",
      "Input Impedance (Balanced)": "20kΩ",
      "Input Gain Amplification Range": "24 to -27dB, (3dB Step, 17 in total)",
      "Operating Power Supply": "AC110/220V, 50Hz/60Hz",
      "Enclosure / Chassis Material": "Pressed Steel (powder coated)",
      "Chassis Dimensions (H×W×D)": "45×482×258 mm, Size 19” 1RU",
      "Product Weight": "2.9 kg",
      "Included Accessories": "IEC 1.2 MTR Power Cord",
      "Environmental Conditions": "-10 to +40 °C",
      Compliance: "CE & RoHS",
      "Analog Input Channel": 8,
      "Analog Output Channel": 8,
      "Dante Input Channel": 8,
      "Dante Output Channel": 8,
      "Ethernet Control Port": 1,
      "Dante Interface (Primary)": 1,
      "Dante Interface (Secondary)": 1,
      RS232: 1,
      RS485: 1,
      GPIO: 8,
    },
    keyFeatures: [
      "DSP audio processing",
      "Built-in automatic mixing console",
      "Ducker dodger",
      "Optional feedback elimination",
      "Echo elimination",
      "Noise elimination module",
      "Input Per Channel: Preamplifier, signal generator, expander, compressor, 10-band parametric equalization",
      "Output Per Channel: 31-band graphic equalizer, delay, crossover, limiter",
      "Built-in bi-directional USB Audio Interface for soft codec conferencing solution supports recording & play",
      "Built-in 8x8 Dante audio module",
      "Support for scene preset function",
      "Automatic power failure protection memory function",
      "Full-featured matrix mixing function",
      "User definable GUI windows-based control software to manage & configure the DSP unit",
      "Built-in automatic camera tracking function",
    ],
    image: require("../../assets/Keyer/Keyer-1616/1616 front.png"),
    download:
      "https://drive.google.com/file/d/1AjPkoGpY5enpCRobOHxhqbDY9aM2ebv5/view?usp=drive_link",
  },
  {
    name: "Parameter Controller",
    productName: "Keyer",
    des: ["Wall Mount Controller for Keyer DSP"],
    category: "DSP & Controls",
    description:
      "The PC1 is a wall-mount control panel that acts as a remote-control device for the Keyer Series of DSPs. It can be customized to suit various applications like processor volume or switching application scenes, mixing matrix, and other functions. It communicates with the DSP unit through UDP commands on standard network cable Cat5e or Cat6 & can be powered up through a POE switch on the same cable.",
    technicalSpecification: {
      "Operating Temperature": "-10 to 40",
      "Operating Power": "PoE (IEEE 802.3af)",
      "IP Control": "UDP",
      "Control Cable": "RJ-45 (CAT-5/6/7 Network cable)",
      "Control Line Length": "≤100m",
      "Screen Size": "1.3",
      "Control Knob": 1,
      Material: "Aluminum alloy sandblasting",
      Color: "Black",
      Dimension: "86mm*25.65mm*105mm",
    },
    keyFeatures: [
      "Fully customizable front panel knob to adjust various parameters of DSP it is connected to.",
      "Works on UDP protocol through standard network cable",
      "Powered by POE switch so no need of separate power cable or supply unit.",
    ],
    image: require("../../assets/Keyer/Keyer-1616/1616.png"),
    download: "https://example.com/download.pdf",
  },

  // Novo Conference System

  {
    name: "NCS 5C",
    productName: "Novo",
    des: "Chairman microphone unit for Novo Conference System. ",
    category: "Audio Conference System",
    description:
      "The NCS-5C is a desktop base discussion microphone unit designed as a chairman microphone for Novo Conference System. The microphone unit is engineered in high-quality aluminum alloy die cast housing. The chairman microphone connects to the NCS-110 central control unit via network category 5 cable. The unit includes a shotgun Gooseneck microphone with a cardioid unidirectional pickup capsule. The microphone comes with an illuminating ring at the bottom which indicates the active status. The chairman unit prioritizes itself over all other delegate units via override button.",
    technicalSpecification: {
      "Polar Pattern": "Cardioid Condenser",
      "Frequency Response": "50Hz-20KHz",
      Sensitivity: "-20dBV (+/-3dB) (0dB=1Vpa, f=1KHz)",
      "Maximum Input Sound Pressure Level": "110dB (THD < 5%, f=1KHz)",
      "Signal to Noise Ratio (A-weighted)": ">100dBA (THD<1%, f=1KHz)",
      Distortion: "<0.1%",
      "Power Supply": "24V DC (supplied by the controller)",
      "Power Consumption": "0.72W",
      "Unit Interface": "RJ45 network input",
      Weight: "about 670g",
      "Dimensions (mm)": "147 (L) x 115 (W) x 218 (H)",
    },
    keyFeatures: [
      "Wire Integrated Gooseneck microphone with cardioid pickup capsule for clear and full sound quality",
      "High sensitivity and good long-distance pick-up effect",
      "Speaking status indicator: Red when mute, Green when speaking",
      "Convenient loop through cabling via standard Cat5 category",
      "In-built mute button with status LED",
      "Aluminum finished metallic die-cast body",
    ],
    image: require("../../assets/Novo/NCS-5C/NCS-5C front.png"),
    download:
      "https://drive.google.com/file/d/1FnK94c6gEtd1PqvNgRfoKUfm0UrasdCv/view?usp=drive_link",
  },
  {
    name: "NCS 5D",
    productName: "Novo",
    des: "Delegate Microphone Unit for Novo Conference System. ",
    category: "Audio Conference System",
    description:
      "The NCS-5D is a desktop base discussion microphone unit designed as a delegate microphone for Novo Conference System. The microphone unit is engineered in high-quality aluminum alloy die cast housing. The delegate microphone connects to the NCS-110 central control unit via network category 5 cable. The unit includes a shotgun Gooseneck microphone with a cardioid unidirectional pickup capsule. The microphone comes with an illuminating ring at the bottom which indicates the active status. The delegate unit has a mute button to control its integrated microphone.",
    technicalSpecification: {
      "Polar pattern": "Cardioid Condenser",
      "Frequency response": "50Hz-20KHz",
      Sensitivity: "-20dBV (+/-3dB) (0db=1Vpa, f=1Khz)",
      "Maximum input sound pressure level": "110dB (THD < 5%, f=1KHz)",
      "Signal to noise ratio (A-weighted)": ">100dBA (THD<1%, f=1KHz)",
      Distortion: "<0.1%",
      "Power supply": "24V DC (supplied by the controller)",
      "Power consumption": "0.72W",
      "Unit interface": "RJ45 network input",
      Weight: "about 670g",
      "Dimensions (mm)": "147 (L) X 115 (W) x 218 (H)",
    },
    keyFeatures: [
      "Integrated Gooseneck microphone with cardioid pickup capsule for clear and full sound quality, high sensitivity, and a good long-distance pick-up effect.",
      "Speaking status indicator: Red when mute, Green when speaking.",
      "Convenient loop-through cabling via standard cat5 category.",
      "NCS-5C chairman unit has the priority to override all delegate units.",
      "Aluminum finished metallic die-cast body.",
    ],
    image: require("../../assets/Novo/NCS-5C/NCS-5C back.png"),
    download:
      "https://drive.google.com/file/d/1et_yZ6VsEbuD2bZiFn1GrCceTDGY7Dml/view?usp=drive_link",
  },
  {
    name: "NCS-110CU",
    productName: "Novo",
    des: "Central Controller Unit for Novo Conference System.",
    category: "Audio Conference System",
    description:
      "NCS110-CU is the central controller unit of Novo Conference System which powers, manages and controls the whole conference system. The latest microprocessor chip automatically detects the number of units connected, current conference mode, controls cameras connected to it and many other functions which are required in a modern-day conference room. It’s built in Audio Gain Processing circuit prevents unnecessary feedback and improves the vocal intelligibility of the room. Everything functions and parameter in this unit can be easily accessed through the front OLED display which shows the microphone status, operating mode, number of active speakers etc. Housed in a pressed steel body with 1RU size NCS110-CU is designed based on “everything built into hardware” where the complete system is made to run like an appliance without much technical support required.",
    technicalSpecification: {
      "Number of microphones supported": 110,
      "Maximum Power consumption": "100W/24V",
      "XLR balanced carbon maximum output level": "14.6dBu",
      "Maximum output level of the 6.35mm balance socket": "14.6dBu",
      "Microphone unit extension": "Anti-drop 9P aviation plug x 1",
      "Network port (female)": "XLR",
      "Video input port": "BNC x 4",
      "Video output port": "BNC x 1",
      "Video interface impedance": "75Ω",
      "Dante interface": "RJ45 x 1",
      "Audio output": "XLRM x 1, 6.35mm jack x 1, RCA Lotus x 1",
      "Audio input": "RCA Lotus x 1",
      "Pin serial port control interface": "DB9 Female plug x 1",
      "Rs-232 control protocol interface": "5P Phoenix terminal X 1",
      "Rs-422 control protocol interface": "5P Phoenix terminal X 1",
      "Supply voltage": "90-264V AC or 127-370V AC, 47-63Hz",
      Weight: "about 2.3kg",
      "Dimensions (mm)": "410(W) X 43(H) x 206(D)",
    },
    keyFeatures: [
      "4 kinds of conference mode selection: FIFO, Automatic (with limiting time), Request and Sound activated.",
      "The central controller can select the number of speakers, and active 2/3/4 microphones simultaneously.",
      "Support camera tracking, through the serial port RS-232 or RS-422 communication protocol, controls up to 4 cameras, compatible with VISCA, PELCO-D, and PELCO-P 3 kinds of camera control code protocol.",
      "With 4 Video inputs and 1 output port, SD and HD SDI video inputs and outputs are supported.",
      "Supports Dante digital output, flexible to connect with various Dante enabled solutions.",
      "With automatic gain audio processing circuit, prevent feedback effectively and improve the clarity of the whole system.",
      "It is easy to expand and change the configuration. The central controller connects up to 40 microphone units. If connected to the NEB-124W can connect up to 110 microphone units.",
      "With aux input and output, you can plug external audio sources to add multiple functionality like recording, PA/Music inclusion, etc.",
    ],
    image: require("../../assets/Novo/NEB-124/NEB-124W front.png"),
    download:
      "https://drive.google.com/file/d/1f0X3adEZjFMyXDSSL8bjBbARfhYyd6v_/view?usp=drive_link",
  },
  {
    name: "NEB-124W",
    productName: "Novo",
    des: "Power repeater for up to 30 units for Novo Conference System",
    category: "Audio Conference System",
    description:
      "The NEB-124W is a repeater used in the Novo Conference System to provide a power connection for up to 30 microphone units. It enhances the stability of the entire system and increases the number of microphone units used which otherwise can’t be powered by NCS 110CU alone. NEB-124W repeater is made of pressed steel metal housing, which is sturdy, and stylish. It can be fixed on the wall or the bottom of the table etc., which is convenient for installation purposes.",
    technicalSpecification: {
      Model: "NEB-124W",
      AC: "110-240V, 50/60Hz",
      OutputVoltage: "24V",
      MaximumOutputPower: "72W",
      InputOutputTerminal: "RJ45 Network port",
      Length: 220,
      Width: 140,
      Height: 48,
      Weight: "950 gm",
    },
    keyFeatures: [
      "Built-in 72W/24V power module, providing power for 30 microphone units.",
      "Two network cable connectors connected by a dedicated network cable, with one serving as the input and the other as the output.",
      "Built-in fan for effective heat dissipation when operating at high power.",
      "Working indicator: Red light during standby, and blue light when actively working.",
    ],
    image: require("../../assets/Novo/NEB-124/NEB-124W back.png"),
    download:
      "https://drive.google.com/file/d/1cpbBn5o7HuQEC_mn3a_YnhmWVyGtNG2H/view?usp=drive_link",
  },

  // Vector
  {
    name: "AR 31",
    productName: "Vector",
    des: [
      "Introducing the AR 31 Wireless Microphone System with Advanced Features:",
      "- Automatic Frequency Selection (AFS): Press the “/” button for 3 seconds, and the receiver will perform an automatic scan, locking onto an open, interference-free frequency for optimal performance.",
      "- Compatible Systems: With the capability to use multiple frequency bands in one venue, the AR 31 supports up to 24 sets simultaneously, ensuring a seamless and interference-free audio experience.",
      "- IR Infrared Sync: Easily pair the receiver frequency with the transmitter by pressing the [IR] button, simplifying setup and synchronization for hassle-free operation.",
      "- Full Band Transmitter: Equipped with a 134MHz full band transmitter, the AR 31 allows pairing with the receiver irrespective of the frequency band, providing versatility and flexibility.",
      '- Anti-Interference: Featuring a PLL (Phase Lock Loop) frequency control design, the AR 31 ensures transmission reliability. The "NoiseLock" squelch effectively blocks stray RF, maintaining clear and crisp audio.',
      "- Energy Conservation: Switch to the Low RF power mode to double the battery life, offering up to 14 hours* on AA Alkaline Batteries. This energy-efficient design ensures prolonged use without compromising performance.",
    ],
    category: "Wireless Microphone Systems",
    description:
      "AR3 is a 1/2 EIA standard Rack Unit metal chassis single-channel wireless receiver for AR1 & AR2 transmitters. Bright & intuitive LCD front panel display gives necessary information like RF level, Audio levels, working channel & transmitter battery status, etc. With 32MHz operating bandwidth, each receiver band allows up to 10 compatible systems which are interference-free. With multiple bands, it can reach up to 24 compatible systems*. The PLL synthesized circuitry ensures RF transmission reliability with separation from GSM & other EMI interference. AFS (Auto Frequency Selection) functions scan the environment and lock itself in an open interference-free frequency channel. The diversity antenna circuit chooses the better one receiving out of its 1/2 Wave Antennae to give optimum RF stability every time.",
    technicalSpecification: {
      "Carrier Frequency Range": "522MHz~936MHz",
      "Modulation Mode": "FM stere modulation",
      Oscillation: "PLL synthesized",
      Sensitivity: "5dBμV, S/N>60dB at 25 deviation",
      "Operating Bandwidth": "32MHz (E, I, J, K)",
      "Max. Deviation Range": "±45KHz",
      "S/N Ratio": ">105dB",
      "T. H. D": "<0.7%@1KHz",
      "Frequency Response (audio)": "45Hz-18KHz ±3dB",
      "Operating Range": "100M typical*",
      "Power Supply": "DC 12V/12W adapter",
      "Dimension (mm)": "20 (W)x206(D)x43(H)",
      Weight: "Approximately 1.0kg",
      "Output Connector": "XLR balanced & 6.3φ phone jack unbalanced",
      Housing: "Pressed steel powder coated enclosure",
    },
    keyFeatures: [
      "Key Features",
      "AFS (Automatic Frequency Selection)",
      "Press the “AFS” (Auto Frequency Selection) button 3 sec and the receiver will auto-scan and lock on to an open, interference-free frequency.",
      "Compatible systems",
      "Maximum 24 sets can be used simultaneously by using multiple frequency bands in one venue.",
      "IR Infrared Sync",
      "Press [IR] button to automatically pair the receiver frequency with the transmitter.",
      "Full Band Transmitter",
      "134MHz full band transmitter allows pairing with the receiver irrespective of frequency band.",
      "Anti-Interference",
      "PLL (Phase Lock Loop frequency control) design ensures transmission reliability, “NoiseLock”squelch effectively blocks stray RF.",
      "Energy Conservation",
      "Low RF power mode gives twice the battery life of up to 14 hours*. (On AA Alkaline Batteries)",
    ],
    image: require("../../assets/Arche/Arche-31/Ar31.png"),
    download:
      "https://drive.google.com/file/d/1UNgmmpi69DCYuxc9GulFa8Ogw4fi6kBN/view?usp=drive_link",
  },
  {
    name: "AR 32",
    productName: "Vector",
    des: [
      "Introducing the AR 31 Wireless Microphone System with Advanced Features:",
      "- AFS (Automatic Frequency Selection) : Press the “/“ button for 3 sec and the receiver will auto-scan and lock on to an open, interference-free frequency.",
      "- Compatible systems : Maximum 24 sets can be used simultaneously by using multiple frequency bands in one venue.",
      "- IR Infrared Sync : Press [IR] button to automatically pair the receiver frequency with the transmitter.",
      "- Full Band Transmitter : 134MHz full band transmitter allows pairing with the receiver irrespective of frequency band.",
      "- Anti-Interference : PLL (Phase Lock Loop frequency control) design ensures transmission reliability, “NoiseLock”squelch effectively blocks stray RF.",
      "- Energy Conservation : Low RF power mode gives twice the battery life of up to 14 hours*. (On AA Alkaline Batteries)",
    ],
    category: "Wireless Microphone Systems",
    description:
      "AR3 is a 1/2 EIA standard Rack Unit metal chassis single-channel wireless receiver for AR1 & AR2 transmitters. Bright & intuitive LCD front panel display gives necessary information like RF level, Audio levels, working channel & transmitter battery status, etc. With 32MHz operating bandwidth, each receiver band allows up to 10 compatible systems which are interference-free. With multiple bands, it can reach up to 24 compatible systems*. The PLL synthesized circuitry ensures RF transmission reliability with separation from GSM & other EMI interference. AFS (Auto Frequency Selection) functions scan the environment and lock itself in an open interference-free frequency channel. The diversity antenna circuit chooses the better one receiving out of its 1/2 Wave Antennae to give optimum RF stability every time.",
    technicalSpecification: {
      "Carrier Frequency Range": "522MHz~936MHz",
      "Modulation Mode": "FM stere modulation",
      Oscillation: "PLL synthesized",
      Sensitivity: "5dBμV, S/N>60dB at 25 deviation",
      "Operating Bandwidth": "32MHz (E, I, J, K)",
      "Max. Deviation Range": "±45KHz",
      "S/N Ratio": ">105dB",
      "T. H. D": "<0.7%@1KHz",
      "Frequency Response (audio)": "45Hz-18KHz ±3dB",
      "Operating Range": "100M typical*",
      "Power Supply": "DC 12V/12W adapter",
      "Dimension (mm)": "20 (W)x206(D)x43(H)",
      Weight: "Approximately 1.0kg",
      "Output Connector": "XLR balanced & 6.3φ phone jack unbalanced",
      Housing: "Pressed steel powder coated enclosure",
    },
    keyFeatures: [
      "Key Features",
      "AFS (Automatic Frequency Selection)",
      "Press the “AFS” (Auto Frequency Selection) button 3 sec and the receiver will auto-scan and lock on to an open, interference-free frequency.",
      "Compatible systems",
      "Maximum 24 sets can be used simultaneously by using multiple frequency bands in one venue.",
      "IR Infrared Sync",
      "Press [IR] button to automatically pair the receiver frequency with the transmitter.",
      "Full Band Transmitter",
      "134MHz full band transmitter allows pairing with the receiver irrespective of frequency band.",
      "Anti-Interference",
      "PLL (Phase Lock Loop frequency control) design ensures transmission reliability, “NoiseLock”squelch effectively blocks stray RF.",
      "Energy Conservation",
      "Low RF power mode gives twice the battery life of up to 14 hours*. (On AA Alkaline Batteries)",
    ],
    image: require("../../assets/Arche/Arche-32/AR32.png"),
    download:
      "https://drive.google.com/file/d/1aOBFmLVdC00hl3wRUOjH-iQrUJ_7x0Nl/view?usp=drive_link",
  },
  {
    name: "AR 331",
    productName: "Vector",

    des: [
      "Introducing the AR 31 Wireless Microphone System with Advanced Features:",
      "-AFS (Automatic Frequency Selection) : Press the “/“ button for 3 sec and the receiver will auto-scan and lock on to an open, interference-free frequency.",
      "- Compatible systems : Maximum 24 sets can be used simultaneously by using multiple frequency bands in one venue.",
      "- IR Infrared Sync : Press [IR] button to automatically pair the receiver frequency with the transmitter.",
      "- Full Band Transmitter : 134MHz full band transmitter allows pairing with the receiver irrespective of frequency band.",
      "- Anti-Interference : PLL (Phase Lock Loop frequency control) design ensures transmission reliability, “NoiseLock”squelch effectively blocks stray RF.",
      "- Energy Conservation : Low RF power mode gives twice the battery life of up to 14 hours*. (On AA Alkaline Batteries)",
    ],
    category: "Wireless Microphone Systems",
    description:
      "AR33 is a dual channel wireless receiver for AR1 & AR2 transmitters housed in 1 EIA standard Rack Unit metal chassis. Bright & intuitive LCD front panel display gives the necessary information for both the transmitters like RF level, Audio levels, working channel & transmitter battery status, etc. With 32MHz operating bandwidth for each receiver, the band allows up to 10 compatible systems which are interference-free. With multiple bands, it can reach up to 24 compatible systems*. The PLL synthesized circuitry ensures RF transmission reliability with separation from GSM & other EMI interference. AFS (Auto Frequency Selection) functions scan the environment and lock itself in an open interference-free frequency channel. The diversity antenna circuit chooses the better one receiving out of its 1/2 Wave Antennae to give optimum RF stability every time.",
    technicalSpecification: {
      "Mainframe Size": "EIA Standard 1U",
      Channels: "Dual Channel",
      "Frequency Stability": "±0.0005% (0~50 °C)",
      "Carrier Frequency Range": "522MHz~936MHz",
      "Modulation Mode": "FM stereo modulation",
      Oscillation: "PLL synthesized",
      "Receiving Sensitivity": "5dBuv, S/N>60dB",
      Bandwidth: "at 25 deviation 32MHz",
      "Max. Deviation Range": "±45KHz",
      "S/N Ratio": ">105dB",
      "Total Harmonic Distortion (T.H.D)": "<0.7%@1KHz",
      "Frequency Response": "80Hz-18KHz ±3dB",
      "Operating Range": "80~100M typical (in open space)",
      "Power Supply": "DC 12V/12W",
      Weight: "1.9kg",
      "Dimension (mm)": "410(W) x 206 (D) x 43 (H)",
      "Output Connector": "XLR balanced & 6.3 φ phone jack unbalanced",
    },
    keyFeatures: [
      "AFS (Automatic Frequency Selection)",
      "Press the “AFS” (Auto Frequency Selection) button 3 sec and the receiver will auto-scan and lock on to an open, interference-free frequency.",
      "Compatible Systems",
      "Maximum 24 sets can be used simultaneously by using multiple frequency bands in one venue.",
      "IR Infrared Sync",
      "Press [IR] button to automatically pair the receiver frequency with the transmitter.",
      "Full Band Transmitter",
      "134MHz full band transmitter allows pairing with the receiver irrespective of frequency band.",
      "Anti-Interference",
      "PLL (Phase Lock Loop frequency control) design ensures transmission reliability, “NoiseLock” squelch effectively blocks stray RF.",
      "Energy Conservation",
      "Low RF power mode gives twice the battery life of up to 14 hours*. (On AA Alkaline Batteries)",
    ],
    image: require("../../assets/Arche/Arche-331/AR331.png"),
    download:
      "https://drive.google.com/file/d/1KaAtpZaUaNC_3BJBwJCzZ94RHpYPcOAq/view?usp=drive_link",
  },
  {
    name: "AR 332",
    productName: "Vector",

    des: [
      "Introducing the AR 31 Wireless Microphone System with Advanced Features:",
      "-AFS (Automatic Frequency Selection) : Press the “/“ button for 3 sec and the receiver will auto-scan and lock on to an open, interference-free frequency.",
      "- Compatible systems : Maximum 24 sets can be used simultaneously by using multiple frequency bands in one venue.",
      "- IR Infrared Sync : Press [IR] button to automatically pair the receiver frequency with the transmitter.",
      "- Full Band Transmitter : 134MHz full band transmitter allows pairing with the receiver irrespective of frequency band.",
      "- Anti-Interference : PLL (Phase Lock Loop frequency control) design ensures transmission reliability, “NoiseLock”squelch effectively blocks stray RF.",
      "- Energy Conservation : Low RF power mode gives twice the battery life of up to 14 hours*. (On AA Alkaline Batteries)",
    ],
    category: "Wireless Microphone Systems",
    description:
      "AR33 is a dual channel wireless receiver for AR1 & AR2 transmitters housed in 1 EIA standard Rack Unit metal chassis. Bright & intuitive LCD front panel display gives the necessary information for both the transmitters like RF level, Audio levels, working channel & transmitter battery status, etc. With 32MHz operating bandwidth for each receiver, the band allows up to 10 compatible systems which are interference-free. With multiple bands, it can reach up to 24 compatible systems*. The PLL synthesized circuitry ensures RF transmission reliability with separation from GSM & other EMI interference. AFS (Auto Frequency Selection) functions scan the environment and lock itself in an open interference-free frequency channel. The diversity antenna circuit chooses the better one receiving out of its 1/2 Wave Antennae to give optimum RF stability every time.",
    technicalSpecification: {
      "Mainframe Size": "EIA Standard 1U",
      Channels: "Dual Channel",
      "Frequency Stability": "±0.0005% (0~50 °C)",
      "Carrier Frequency Range": "522MHz~936MHz",
      "Modulation Mode": "FM stereo modulation",
      Oscillation: "PLL synthesized",
      "Receiving Sensitivity": "5dBuv, S/N>60dB",
      Bandwidth: "at 25 deviation 32MHz",
      "Max. Deviation Range": "±45KHz",
      "S/N Ratio": ">105dB",
      "Total Harmonic Distortion (T.H.D)": "<0.7%@1KHz",
      "Frequency Response": "80Hz-18KHz ±3dB",
      "Operating Range": "80~100M typical (in open space)",
      "Power Supply": "DC 12V/12W",
      Weight: "1.9kg",
      "Dimension (mm)": "410(W) x 206 (D) x 43 (H)",
      "Output Connector": "XLR balanced & 6.3 φ phone jack unbalanced",
    },
    keyFeatures: [
      "AFS (Automatic Frequency Selection)",
      "Press the “AFS” (Auto Frequency Selection) button 3 sec and the receiver will auto-scan and lock on to an open, interference-free frequency.",
      "Compatible Systems",
      "Maximum 24 sets can be used simultaneously by using multiple frequency bands in one venue.",
      "IR Infrared Sync",
      "Press [IR] button to automatically pair the receiver frequency with the transmitter.",
      "Full Band Transmitter",
      "134MHz full band transmitter allows pairing with the receiver irrespective of frequency band.",
      "Anti-Interference",
      "PLL (Phase Lock Loop frequency control) design ensures transmission reliability, “NoiseLock” squelch effectively blocks stray RF.",
      "Energy Conservation",
      "Low RF power mode gives twice the battery life of up to 14 hours*. (On AA Alkaline Batteries)",
    ],
    image: require("../../assets/Arche/Arche-332/AR332.png"),
    download:
      "https://drive.google.com/file/d/1Fw_fNaB_vcr0V4LJYmb18LAZKJx_nKx4/view?usp=drive_link",
  },
];

export default dummyProducts;
